// GENERATED by apps/gateway/protocol/export_ts.py — do not edit by hand.
// schema-sha256: f55f0b4cb163eea377ffb837748189ed381cf9cf0ecbc2113f6dd60873010646
// Regenerate: cd apps/gateway && uv run python -m protocol.export_ts

export const PROTOCOL_VERSION = 1;
export const MAX_FRAME_BYTES = 65536;

export type Channel = "quotes" | "orders" | "session" | "ai" | "voice";

export interface Envelope {
  v?: number;
  t: string;
  seq: number;
  ts: number;
  ch: "quotes" | "orders" | "session" | "ai" | "voice";
  cid?: string | null;
  p?: Record<string, unknown>;
}

/** `ai.advice` — s2c, channel `ai`. */
export interface AiAdvice {
  cid?: string | null;
  kind: "research" | "plan" | "advise" | "news" | "coach";
  text: string;
  citations?: string[];
  ts: number;
}

/** `ai.ask` — c2s, channel `ai`. */
export interface AiAsk {
  kind: "research" | "plan" | "advise" | "news" | "coach";
  sym?: string | null;
  tf?: string | null;
}

/** `candle` — s2c, channel `quotes`. */
export interface Candle {
  sym: string;
  tf: string;
  o: number;
  h: number;
  l: number;
  c: number;
  ts: number;
}

/** `error` — s2c, channel `session`. */
export interface Error {
  code: string;
  message: string;
  cid?: string | null;
}

/** `grade` — s2c, channel `session`. */
export interface Grade {
  cid: string;
  playbookId: string;
  required_pass: number;
  required_total: number;
  clean: boolean;
  results?: Record<string, unknown>[];
}

/** `grade.answer` — c2s, channel `session`. */
export interface GradeAnswer {
  cid: string;
  ruleId: string;
  answer: boolean;
}

/** `hello` — c2s, channel `session`. */
export interface Hello {
  token: string;
  lastSeq?: number | null;
  clientVersion?: string | null;
}

/** `intent.close` — c2s, channel `orders`. */
export interface IntentClose {
  positionId: number;
  clutch: true;
  armedAt: number;
}

/** `intent.modify` — c2s, channel `orders`. */
export interface IntentModify {
  positionId: number;
  sl?: number | null;
  tp?: number | null;
  clutch: true;
  armedAt: number;
}

/** `intent.open` — c2s, channel `orders`. */
export interface IntentOpen {
  sym: string;
  side: "buy" | "sell";
  type?: "market";
  lots: number;
  relativeSl?: number | null;
  relativeTp?: number | null;
  clutch: true;
  armedAt: number;
}

/** `intent.panic` — c2s, channel `orders`. */
export interface IntentPanic {
  clutch: true;
  armedAt: number;
}

/** `journal.memo.link` — c2s, channel `voice`. */
export interface JournalMemoLink {
  voiceId: string;
  cid: string;
}

/** `maint` — s2c, channel `session`. */
export interface Maint {
  active: boolean;
  until?: number | null;
  note?: string | null;
}

/** `news.item` — s2c, channel `ai`. */
export interface NewsItem {
  id: string;
  title: string;
  url: string;
  source: string;
  ts: number;
}

/** `order.ack` — s2c, channel `orders`. */
export interface OrderAck {
  cid: string;
  orderId?: number | null;
  positionId?: number | null;
  sym: string;
  side: "buy" | "sell";
  lots: number;
  price?: number | null;
  ts: number;
}

/** `order.reject` — s2c, channel `orders`. */
export interface OrderReject {
  cid: string;
  reason: string;
  detail?: string | null;
  ts: number;
}

/** `order.upd` — s2c, channel `orders`. */
export interface OrderUpd {
  cid?: string | null;
  orderId?: number | null;
  positionId?: number | null;
  state: string;
  ts: number;
}

/** `pad.telemetry` — c2s, channel `session`. */
export interface PadTelemetry {
  ts: number;
  from: string;
  to: string;
  sym?: string | null;
  lots?: number | null;
  reason?: string | null;
  clutchMs: number;
  armMs: number;
  clutchCycles: number;
  armFlips: number;
  btnRateHz: number;
  lotStepsSince: number;
  ttfMs?: number | null;
}

/** `ping` — c2s, channel `session`. */
export interface Ping {
  visible: boolean;
  pad: boolean;
  clutch: boolean;
}

/** `playbook.list` — s2c, channel `session`. */
export interface PlaybookList {
  playbooks?: Record<string, unknown>[];
}

/** `playbook.select` — c2s, channel `session`. */
export interface PlaybookSelect {
  playbookId: string;
  cid?: string | null;
}

/** `pnl` — s2c, channel `session`. */
export interface Pnl {
  balance: number;
  equity: number;
  openPnl: number;
  dayPnl?: number | null;
  ts: number;
}

/** `pong` — s2c, channel `session`. */
export interface Pong {
  ts: number;
}

/** `pos.snap` — s2c, channel `orders`. */
export interface PosSnap {
  positions?: Record<string, unknown>[];
  ts: number;
}

/** `quote` — s2c, channel `quotes`. */
export interface Quote {
  sym: string;
  bid: number;
  ask: number;
  ts: number;
}

/** `resync` — c2s, channel `session`. */
export interface Resync {
  lastSeq: number;
}

/** `risk` — s2c, channel `session`. */
export interface Risk {
  maxLots: number;
  maxPositions: number;
  positions: number;
  dayLossUsd: number;
  maxDayLossUsd: number;
  blocked?: string[];
}

/** `score.session` — s2c, channel `session`. */
export interface ScoreSession {
  axes?: Record<string, number>;
  total: number;
  na?: string[];
  weightsVersion: string;
}

/** `sentinel.tick` — s2c, channel `ai`. */
export interface SentinelTick {
  sym: string;
  spread: number;
  state: string;
  ts: number;
}

/** `session` — s2c, channel `session`. */
export interface Session {
  open: boolean;
  locked: boolean;
  reason?: string | null;
  startsAt?: number | null;
  endsAt?: number | null;
}

/** `session.lock` — c2s, channel `session`. */
export interface SessionLock {
  reason?: string | null;
}

/** `session.unlock` — c2s, channel `session`. */
export interface SessionUnlock {
  reason?: string | null;
}

/** `signal.item` — s2c, channel `ai`. */
export interface SignalItem {
  id: string;
  kind: "volman" | "tv";
  sym: string;
  text: string;
  ts: number;
}

/** `snap` — c2s, channel `session`. */
export interface Snap {
  what?: "positions" | "session" | "all";
}

/** `sub` — c2s, channel `session`. */
export interface Sub {
  ch: "quotes" | "orders" | "session" | "ai" | "voice";
  syms?: string[];
}

/** `tilt` — s2c, channel `session`. */
export interface Tilt {
  score: number;
  band: "calm" | "warm" | "hot" | "scorched";
  top?: string[];
  cooldownUntil?: number | null;
}

/** `voice.begin` — c2s, channel `voice`. */
export interface VoiceBegin {
  voiceId: string;
  cid?: string | null;
}

/** `voice.cancel` — c2s, channel `voice`. */
export interface VoiceCancel {
  voiceId: string;
}

/** `voice.state` — s2c, channel `voice`. */
export interface VoiceState {
  busy: boolean;
  queued: number;
}

/** `voice.transcript` — s2c, channel `voice`. */
export interface VoiceTranscript {
  voiceId: string;
  cid?: string | null;
  ok: boolean;
  text?: string | null;
  reason?: string | null;
  durMs: number;
  sttMs: number;
}

/** `welcome` — s2c, channel `session`. */
export interface Welcome {
  seq: number;
  serverTime: number;
  resumed?: boolean;
  mode?: "demo";
}

export interface MessageMap {
  "ai.advice": AiAdvice;
  "ai.ask": AiAsk;
  "candle": Candle;
  "error": Error;
  "grade": Grade;
  "grade.answer": GradeAnswer;
  "hello": Hello;
  "intent.close": IntentClose;
  "intent.modify": IntentModify;
  "intent.open": IntentOpen;
  "intent.panic": IntentPanic;
  "journal.memo.link": JournalMemoLink;
  "maint": Maint;
  "news.item": NewsItem;
  "order.ack": OrderAck;
  "order.reject": OrderReject;
  "order.upd": OrderUpd;
  "pad.telemetry": PadTelemetry;
  "ping": Ping;
  "playbook.list": PlaybookList;
  "playbook.select": PlaybookSelect;
  "pnl": Pnl;
  "pong": Pong;
  "pos.snap": PosSnap;
  "quote": Quote;
  "resync": Resync;
  "risk": Risk;
  "score.session": ScoreSession;
  "sentinel.tick": SentinelTick;
  "session": Session;
  "session.lock": SessionLock;
  "session.unlock": SessionUnlock;
  "signal.item": SignalItem;
  "snap": Snap;
  "sub": Sub;
  "tilt": Tilt;
  "voice.begin": VoiceBegin;
  "voice.cancel": VoiceCancel;
  "voice.state": VoiceState;
  "voice.transcript": VoiceTranscript;
  "welcome": Welcome;
}

export type MessageType = keyof MessageMap;
