"""Generate the web's protocol types from the exported JSON Schema.

The Pydantic catalog is the single source of truth. The HUD does not hand-write these types; it
imports the generated file, and `app/scripts/check-protocol-types.mjs` fails the web build when
the checked-in file no longer matches the schema it was generated from.

    uv run python -m protocol.export_ts --check     # verify freshness
    uv run python -m protocol.export_ts             # rewrite
"""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import sys
from pathlib import Path
from typing import Any

from .export_schema import build_schema

ROOT = Path(__file__).resolve().parents[3]
SCHEMA_PATH = ROOT / "app" / "src" / "protocol" / "schema.json"
TYPES_PATH = ROOT / "app" / "src" / "protocol" / "types.ts"

HEADER = "// GENERATED by apps/gateway/protocol/export_ts.py — do not edit by hand."
HASH_PREFIX = "// schema-sha256: "


def ts_name(wire_type: str) -> str:
    """`intent.open` -> `IntentOpen`; the TS name of one wire message."""
    return "".join(part.capitalize() for part in re.split(r"[.\-_]", wire_type))


def ts_type(schema: dict[str, Any], defs: dict[str, Any]) -> str:
    """Render one JSON Schema node as a TypeScript type."""
    if "$ref" in schema:
        return ts_type(defs[schema["$ref"].rsplit("/", 1)[-1]], defs)
    if "const" in schema:
        return json.dumps(schema["const"])
    if "enum" in schema:
        return " | ".join(json.dumps(v) for v in schema["enum"])
    if "anyOf" in schema:
        return " | ".join(dict.fromkeys(ts_type(s, defs) for s in schema["anyOf"]))

    kind = schema.get("type")
    if kind == "array":
        return f"{ts_type(schema.get('items', {}), defs)}[]"
    if kind == "object":
        extra = schema.get("additionalProperties")
        value = ts_type(extra, defs) if isinstance(extra, dict) else "unknown"
        return f"Record<string, {value}>"
    return {
        "string": "string",
        "number": "number",
        "integer": "number",
        "boolean": "boolean",
        "null": "null",
    }.get(kind, "unknown")


def render_interface(name: str, schema: dict[str, Any], defs: dict[str, Any]) -> str:
    required = set(schema.get("required", []))
    lines = [f"export interface {name} {{"]
    for field, spec in schema.get("properties", {}).items():
        optional = "" if field in required else "?"
        key = field if re.fullmatch(r"[A-Za-z_$][\w$]*", field) else json.dumps(field)
        lines.append(f"  {key}{optional}: {ts_type(spec, defs)};")
    lines.append("}")
    return "\n".join(lines)


def render(schema: dict[str, Any]) -> str:
    digest = hashlib.sha256(
        (json.dumps(schema, indent=2, sort_keys=True) + "\n").encode("utf-8")
    ).hexdigest()

    envelope_defs = schema["envelope"].get("$defs", {})
    out = [
        HEADER,
        f"{HASH_PREFIX}{digest}",
        "// Regenerate: cd apps/gateway && uv run python -m protocol.export_ts",
        "",
        f"export const PROTOCOL_VERSION = {schema['version']};",
        f"export const MAX_FRAME_BYTES = {schema['maxFrameBytes']};",
        "",
        "export type Channel = " + " | ".join(json.dumps(c) for c in schema["channels"]) + ";",
        "",
        render_interface("Envelope", schema["envelope"], envelope_defs),
        "",
    ]

    for wire_type, entry in schema["messages"].items():
        payload = entry["payload"]
        defs = payload.get("$defs", {})
        out.append(f"/** `{wire_type}` — {entry['direction']}, channel `{entry['ch']}`. */")
        out.append(render_interface(ts_name(wire_type), payload, defs))
        out.append("")

    out.append("export interface MessageMap {")
    for wire_type in schema["messages"]:
        out.append(f"  {json.dumps(wire_type)}: {ts_name(wire_type)};")
    out.append("}")
    out.append("")
    out.append("export type MessageType = keyof MessageMap;")
    out.append("")
    return "\n".join(out)


def current_files() -> tuple[str, str]:
    """What the live catalog says the two generated files should contain."""
    schema = build_schema()
    return json.dumps(schema, indent=2, sort_keys=True) + "\n", render(schema)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Generate the web's protocol types")
    parser.add_argument("--check", action="store_true", help="Fail if the checked-in files are stale")
    args = parser.parse_args(argv)

    schema_text, types_text = current_files()
    if args.check:
        for path, expected in ((SCHEMA_PATH, schema_text), (TYPES_PATH, types_text)):
            actual = path.read_text(encoding="utf-8") if path.exists() else ""
            if actual != expected:
                print(
                    f"stale: {path.relative_to(ROOT)} — regenerate with "
                    "`uv run python -m protocol.export_ts`",
                    file=sys.stderr,
                )
                return 1
        return 0

    for path, text in ((SCHEMA_PATH, schema_text), (TYPES_PATH, types_text)):
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8")
        print(f"wrote {path.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
